// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/use-auth";
import AuthGuard from "@/components/custom/auth-guard";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-context";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Criado com a Lasy",
  description: "Projeto criado com Lasy AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning // Adicionando warning suppression ao body
      >
        {/* Usando tag script nativa para evitar conflito de hidratação com o Next.js Script component */}
        <script src="/lasy-bridge.js" />
<script src="/easy-bridge.js" />

{/* 🔴 NOVO: ThemeProvider deve ser o mais externo aqui */}
<ThemeProvider> 
    <AuthProvider>
        <AuthGuard>
            {children}
        </AuthGuard>
    </AuthProvider>
</ThemeProvider>   
<Toaster />
      </body>
    </html>
  );
}