// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mmowytolbxoaoywjmimy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tb3d5dG9sYnhvYW95d2ptaW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNjY2MDYsImV4cCI6MjA3ODY0MjYwNn0.m_DHncmhtCHjTe0t8f3fA4ljikKSC2sxM97LXokFois";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);